branch: true
ignore-not-existing: true
llvm: true
output-type: lcov
ignore:
  - "/*"
  - "C:/*"
  - "../*"
excl-line: "#\\[derive\\("
excl-start: "mod tests \\{"
excl-br-line: "#\\[derive\\("
excl-br-start: "mod tests \\{"
