[workspace]

[package]
name = "iota-wallet-python-binding"
version = "0.1.0"
authors = ["Bing-Yang Lin <bingyang.lin@iota.org>"]
license = "MIT"
edition = "2018"

[lib]
name = "iota_wallet"
crate-type = ["cdylib"]

[dependencies]
iota-wallet = { path = "../../../", version = "0.1.0", features = ["stronghold", "stronghold-storage", "sqlite-storage", "ledger-nano", "ledger-nano-simulator"] }
iota-core = { git = "https://github.com/iotaledger/iota.rs", branch = "dev" }
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1"
once_cell = "1.4"
rand = "0.7"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread"] }
futures = "0.3"
backtrace = "0.3"
hex = "0.4"
dict_derive = "0.3.0"

[dependencies.pyo3]
version = "0.13"
features = ["extension-module", "abi3"]