[workspace]

[package]
name = "iota-wallet-python-binding"
version = "0.1.0"
authors = ["Bing-Yang Lin <bingyang.lin@iota.org>"]
license = "MIT"
edition = "2018"

[lib]
name = "iota_wallet"
crate-type = ["cdylib"]

[patch.'crates-io']
lexical-core = { git = "https://github.com/Gelbpunkt/rust-lexical", branch = "fix-warnings-and-update-deps" }

[dependencies]
iota-wallet = { path = "../../../", version = "0.1.0", features = ["stronghold", "stronghold-storage", "sqlite-storage", "ledger-nano", "ledger-nano-simulator"] }
iota-core = { git = "https://github.com/iotaledger/iota.rs", branch = "dev" }
chrono = "0.4"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread"] }
hex = "0.4"
dict_derive = "0.3.0"

[dependencies.pyo3]
version = "0.13"
features = ["extension-module", "abi3"]